-- MySQL Script generated by MySQL Workbench
-- Fri Jun  2 10:12:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_badge_of_honour
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_badge_of_honour
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_badge_of_honour` DEFAULT CHARACTER SET utf8 ;
USE `db_badge_of_honour` ;

-- -----------------------------------------------------
-- Table `db_badge_of_honour`.`tbl_application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_badge_of_honour`.`tbl_application` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `national_register_nr` CHAR(11) NOT NULL,
  `firstname` VARCHAR(64) NOT NULL,
  `lastname` VARCHAR(64) NOT NULL,
  `birthplace` VARCHAR(64) NOT NULL,
  `main_profession` VARCHAR(120) NOT NULL,
  `job_title` VARCHAR(120) NOT NULL,
  `grade_or_rank` CHAR(50) NOT NULL,
  `initiator` VARCHAR(64) NOT NULL,
  `distinctions_received` LONGTEXT NOT NULL,
  `tot_year_service` TINYINT UNSIGNED NOT NULL,
  `result_evaluation` TEXT NULL DEFAULT NULL,
  `sanctions` TEXT NULL DEFAULT NULL,
  `state` ENUM('GOEDKEURING_1', 'GOEDKEURING_2', 'GOEDKEURING_3', 'GOEDKEURING_4', 'GOEDKEURING_5', 'ADVIES', 'BESLUIT', 'BESLUIT_VERTALEN', 'OORKONDE_OPMAKEN', 'KLAAR', 'AFGEKEURD') CHARACTER SET 'armscii8' NOT NULL,
  `proposed_honorary_distinction` VARCHAR(40) NOT NULL,
  `report_about_involved` TEXT NULL DEFAULT NULL,
  `birthdate` DATE NOT NULL,
  `salary_scale` VARCHAR(20) NOT NULL,
  `tot_month_service` TINYINT NOT NULL,
  `decision` TEXT NULL DEFAULT NULL,
  `decision_translated` TEXT NULL DEFAULT NULL,
  `advice` TEXT NULL DEFAULT NULL,
  `approval_ABB` VARCHAR(6) NULL DEFAULT NULL,
  `approval_minister` VARCHAR(6) NULL DEFAULT NULL,
  `approval_prime_minister` VARCHAR(6) NULL DEFAULT NULL,
  `approval_chancellery` VARCHAR(6) NULL DEFAULT NULL,
  `approval_king` VARCHAR(6) NULL DEFAULT NULL,
  `date_created` DATE NULL DEFAULT NULL,
  `approval_ABB_date` DATE NULL DEFAULT NULL,
  `approval_minister_date` DATE NULL DEFAULT NULL,
  `approval_prime_minister_date` DATE NULL DEFAULT NULL,
  `approval_chancellery_date` DATE NULL DEFAULT NULL,
  `approval_king_date` DATE NULL DEFAULT NULL,
  `city` VARCHAR(64) NOT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `proposed_honorary_distinction_title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_badge_of_honour`.`tbl_career`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_badge_of_honour`.`tbl_career` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `grade` VARCHAR(50) NOT NULL,
  `from_date` DATE NOT NULL,
  `to_date` DATE NOT NULL,
  `performance_breach` DECIMAL(10,0) NOT NULL,
  `nature_performances` VARCHAR(25) NOT NULL,
  `id_application` INT UNSIGNED NOT NULL,
  `function_title` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_application_idx` (`id_application` ASC) VISIBLE,
  CONSTRAINT `id_application`
    FOREIGN KEY (`id_application`)
    REFERENCES `db_badge_of_honour`.`tbl_application` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_badge_of_honour`.`tbl_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_badge_of_honour`.`tbl_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(330) NOT NULL,
  `password` VARCHAR(255) NOT NULL DEFAULT 'null',
  `role` VARCHAR(150) NOT NULL,
  `firstname` VARCHAR(64) NOT NULL,
  `lastname` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_badge_of_honour`.`tbl_certificate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_badge_of_honour`.`tbl_certificate` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `gender_applicant` VARCHAR(45) NOT NULL,
  `job_title_option` CHAR(1) NOT NULL,
  `management` VARCHAR(100) NOT NULL,
  `tot_year_service` INT UNSIGNED NOT NULL,
  `certificate_application_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `certificate_application_id_idx` (`certificate_application_id` ASC) VISIBLE,
  CONSTRAINT `certificate_application_id`
    FOREIGN KEY (`certificate_application_id`)
    REFERENCES `db_badge_of_honour`.`tbl_application` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
