package edu.ap.backendspring.enums;

public enum Role {
    DEVELOPER,
    ONDERZOEKER_ABB,
    ONDERZOEKER_MINISTER,
    ONDERZOEKER_EERSTE_MINISTER,
    ONDERZOEKER_KANSELARIJ,
    ONDERZOEKER_KONING,
    INITIATIEFNEMER,
    ADVISEUR,
    BESLUITNEMER,
    OORKONDEOPMAKER,
    VERTALER,

}